providers = ["php", "node"]

[phases.setup]
nixPkgs = ["php82", "php82Extensions.intl", "php82Extensions.zip", "php82Extensions.pdo_mysql"]

[phases.build]
cmds = [
  "composer install --optimize-autoloader --no-dev",
  "npm install",
  "npm run build"
]

[phases.deploy]
cmds = [
  "php artisan migrate --force",
  "php artisan optimize"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
