[phases.setup]
nixPkgs = ["php83", "php83Extensions.intl", "php83Extensions.zip", "php83Extensions.pdo_mysql", "nodejs", "npm"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-scripts --no-interaction"]

[phases.build]
cmds = ["npm install", "npm run build"]

[start]
cmd = "touch database/database.sqlite && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
